version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: launchtrace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed_data_int.sql:/docker-entrypoint-initdb.d/seed_data_int.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5029:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=launchtrace;Username=postgres;Password=password
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
